version: "3.8"

services:



  backend:
    build: "./server"
    container_name: "serverdocs"
    ports:
      - "3001:3001"
    depends_on:
      - "mongodb"
    # links:
    #   - "mongodb"
    # expose:
    #   - "3001"
    networks:
      - "mynetwork"

  frontend:
    build: "./client"
    container_name: "clientdocs"
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"
    # links:
    #   - "backend"
    # expose:
    #   - "3000"
    networks:
      - "mynetwork"

  mongodb:
    image: "mongo:5.0.3"
    container_name: "mongo"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    # volumes:
    #   - db:/data/db
    # expose:
    #   - "27017"
    networks:
      - "mynetwork"



networks:
    mynetwork:
      external: true
      driver: bridge
